# App
spring.application.name=medicore
server.port=8080

# Database - Supabase Session Pooler (IPv4)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ureuoezigfmnetvdeywx
spring.datasource.password=rsdasrf0622

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=medicore-super-secret-jwt-key-that-is-at-least-32-characters-long-enough
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS
app.cors.allowed-origins=http://localhost:5173