# App
spring.application.name=medicore
server.port=8081

# Database - Supabase Session Pooler (IPv4)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ureuoezigfmnetvdeywx
spring.datasource.password=rsdasrf0622

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=medicore-super-secret-jwt-key-that-is-at-least-32-characters-long-enough
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS
app.cors.allowed-origins=http://localhost:5173


# ?? Google OAuth
google.client-id=431600217501-n72uuai5kjebfokg6ri6h9ge31e44jrq.apps.googleusercontent.com

# ?? Gmail SMTP (Welcome Email)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daclan.rsd@gmail.com
spring.mail.password=ssya gmfk cpjw dbrr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000